'use client';
import { useEffect, useState } from 'react';
const A='/assets/';
const platforms=[['Android','04_feature_android','Your ideas, always within reach. Capture a thought and pick it up anywhere.'],['iOS','05_feature_ios','A little more clarity in your pocket. Designed to feel right at home on iPhone.'],['Windows / Linux','06_feature_windows','Make room for your next big idea. A focused workspace for deeper thinking.'],['Web','07_feature_web','Open a tab. Open your mind. Your entire notebook, wherever you sign in.']];
const plans=[{name:'Starter',price:19,features:['Up to 5 team members','2 project boards','Basic sync updates','7-day activity history','Email support']},{name:'Pro',price:59,features:['Unlimited team members','Unlimited boards & tasks','Smart status automation','Full activity history','Slack & Calendar integration']}];
export default function Site(){
 const [menu,setMenu]=useState(false); const [message,setMessage]=useState('');
 useEffect(() => {
   const reduced = window.matchMedia('(prefers-reduced-motion: reduce)');
   const elements = document.querySelectorAll<HTMLElement>('.section-heading, .preview, .platform, .benefit, .plan, .benefit-art');
   const reveal = new IntersectionObserver(entries => entries.forEach(entry => {
     if (entry.isIntersecting) { entry.target.classList.add('is-visible'); reveal.unobserve(entry.target); }
   }), { threshold: 0.1 });
   if (!reduced.matches) elements.forEach(element => { element.classList.add('reveal'); reveal.observe(element); });
   const header = document.querySelector('header');
   const hero = document.querySelector('.hero');
   const navigation = new IntersectionObserver(([entry]) => header?.classList.toggle('scrolled', !entry.isIntersecting), { rootMargin: '-80px 0px 0px 0px' });
   if (hero) navigation.observe(hero);
   const showAll = () => { if (reduced.matches) elements.forEach(element => element.classList.add('is-visible')); };
   reduced.addEventListener('change', showAll);
   return () => { reveal.disconnect(); navigation.disconnect(); reduced.removeEventListener('change', showAll); elements.forEach(element => element.classList.remove('reveal')); };
 }, []);
 useEffect(() => {
   const close = (event: KeyboardEvent) => { if (event.key === 'Escape') { setMenu(false); setMessage(''); } };
   window.addEventListener('keydown', close);
   return () => window.removeEventListener('keydown', close);
 }, []);
 return <><a className="skip" href="#main">Skip to content</a><header><a href="#" aria-label="Scribblit home"><img className="logo" src={A+'branding/logo-primary.svg'} alt="Scribblit" width="140" height="32"/></a><button className="menu" aria-expanded={menu} aria-label="Toggle navigation" onClick={()=>setMenu(!menu)}>☰</button><nav className={menu?'open':''}>{[['Product','product'],['Features','features'],['Pricing','pricing'],['Resources','resources']].map(([label,id])=><a key={id} href={'#'+id} onClick={()=>setMenu(false)}>{label}</a>)}</nav><a className="button small" href="#pricing">Get Started <span>↗</span></a></header>
 <main id="main"><section className="hero"><div className="hero-content"><span className="badge"><span className="green-dot"/>100K+ active users</span><h1>Ideas. Notes. Clarity.<br/>Wherever your mind goes.</h1><p>Combine note-taking, idea tracking, and daily planning in one smart notebook, ready whenever inspiration hits.</p><div className="tool-pill" aria-label="Capture, organize and plan"><span>✎</span><span>▤</span><span>✓</span><span>⌘</span><span className="pill-word">A little space for everything.</span></div><div className="actions"><button className="button" onClick={()=>setMessage('The iPhone app is not published yet. Explore the product below and choose your plan when you are ready.')}>Download for iPhone <span>↗</span></button><a href="#pricing" className="button secondary">Start Free Trial <span>→</span></a></div></div><div className="hero-bottom"><span>THINK FREELY. FIND CLARITY.</span><a href="#product" aria-label="Explore the product">↓</a></div></section>
 <section className="trust container" aria-label="Our commitments">{[['lock','No Setup Fee'],['shield','100% Legal Compliance'],['users','80%+ Reduced Abuse'],['shield','Cancel Anytime']].map(([icon,text])=><div key={text}><img src={A+'icons/trust/'+icon+'.svg'} width="24" height="24" alt=""/>{text}</div>)}</section>
 <section id="product" className="section container product"><div className="section-heading"><h2>Notes that work<br/>the way you think.</h2><p>From a passing thought to your next big project.<br/>One calm space to bring it all together.</p></div><div className="preview"><img src={A+'ui/10_app_preview.svg'} alt="Scribblit notebook app showing an organized workspace" width="2400" height="1400" loading="lazy"/></div></section>
 <section id="features" className="section container"><div className="section-heading"><h2>Ideas. Notes. Clarity.<br/><span>Wherever your mind goes.</span></h2><p>One notebook. Every device. Always in sync.</p></div><div className="platforms">{platforms.map(([name,file,desc],i)=><article className="platform" key={name}><div className="platform-image"><img src={A+'features/'+file+'.svg'} alt={'Scribblit '+name+' illustration'} width="1600" height="1200" loading="lazy"/></div><div className="platform-copy"><span className="number">0{i+1}</span><h3>Scribblit for {name}</h3><p>{desc}</p><a href="#pricing" aria-label={'Explore Scribblit for '+name}>Explore {name} <span>↗</span></a></div></article>)}</div></section>
 <section className="mountain-cta"><div><span className="badge">A CLEARER WAY TO CREATE</span><h2>How You Take Notes?</h2><p>A spark of inspiration deserves a place to grow.<br/>Make a little room for your next big idea.</p><div className="actions"><a href="#pricing" className="button">Get Started Free <span>↗</span></a><a href="#pricing" className="button secondary">Get Started Pro <span>→</span></a></div></div></section>
 <section className="section container benefits"><div className="section-heading"><h2>Smarter Notes. One Simple Space to<br/><span>Capture, Organize & Remember</span></h2><p>Less searching. More connecting the dots.<br/>Keep what matters close, and let your ideas move forward.</p></div><div className="benefit-grid"><img className="benefit-art" src={A+'features/04_feature_android.svg'} alt="Organized notes, folders and collaborative projects" width="1600" height="1200" loading="lazy"/><div>{[['✎','Smart Note Capture','From quick thoughts to detailed plans, capture inspiration before it slips away.'],['▤','Adaptive Organization','Give every idea a home with intuitive folders and a workspace that grows with you.'],['⌘','Simple & Flexible','A clear canvas without the clutter. Work your way, on whichever device is nearby.']].map(([icon,title,desc])=><article className="benefit" key={title}><span className="benefit-icon">{icon}</span><div><h3>{title}</h3><p>{desc}</p></div></article>)}</div></div></section>
 <section id="pricing" className="section pricing-section"><div className="container"><div className="section-heading"><h2>Choose the best plan</h2><p>Flexible pricing built for every stage, from startup to scale.</p></div><div className="pricing">{plans.map((plan,i)=><article className={'plan '+(i?'pro':'starter')} key={plan.name}><div className="plan-top"><div className="plan-title"><h3>{plan.name}</h3>{i===1&&<span>More room to grow</span>}</div><div className="price">${plan.price}<span>/ month</span></div><p>{i?'For big ideas and the teams behind them.':'A thoughtful start for your everyday work.'}</p></div><div className="plan-details"><h4>What’s included</h4><ul>{plan.features.map(f=><li key={f}><span>✓</span>{f}</li>)}</ul><button className="button" onClick={()=>setMessage(`${plan.name} selected — $${plan.price}/month. Billing is not connected in this workspace, so no payment has been taken.`)}>Get started with {plan.name} <span>↗</span></button></div></article>)}</div><p className="pricing-note">Simple plans. No setup fees. Cancel anytime.</p></div></section></main>
 <footer id="resources"><div className="container"><div className="footer-grid"><div className="footer-brand"><img src={A+'branding/logo-white.svg'} alt="Scribblit" width="158" height="36"/><p>A little space for your thoughts.<br/>A whole world of possibilities.</p><span>Make room for what’s next.</span></div>{[['Product','Features','How It Works','Pricing'],['Company','About','Careers','Contact','Press'],['Resources','Help Center','Updates','Guides','Blog']].map(([title,...links])=><div className="footer-col" key={title}><h3>{title}</h3>{links.map(l=><a key={l} href={l==='Pricing'?'#pricing':l==='Features'?'#features':'#product'}>{l}</a>)}</div>)}</div><div className="footer-bottom"><span>© {new Date().getFullYear()} Scribblit. All rights reserved.</span><div className="socials">{['x','linkedin','youtube','github'].map(s=><a key={s} href={'https://'+(s==='x'?'x.com':s+'.com')} target="_blank" rel="noopener noreferrer" aria-label={s}><img src={A+'icons/social/'+s+'.svg'} alt="" width="30" height="30"/></a>)}</div><a href="#">Back to top ↑</a></div></div></footer>
 {message&&<div className="dialog-backdrop" onClick={()=>setMessage('')}><div role="dialog" aria-modal="true" aria-labelledby="dialog-title" className="dialog" onClick={e=>e.stopPropagation()}><h2 id="dialog-title">Thanks for your interest.</h2><p>{message}</p><button className="button" autoFocus onClick={()=>setMessage('')}>Got it</button></div></div>}</>;
}
